### ISSUE TITLE
host ournetworks.ca on our own server MAR

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#11]
EDIT: From **2018-03-10 call**, 
- [x] @dcwalk set up namecheap dns team _sent SAT MAR 10_
- [x] @garrying manual deploy & https: user for SUN MAR 11
- [x] @patcon get automated website deploy set up for SUN MAR 20? (flexible!)

---
this would allow for:

- https
- fancy things (e.g. #12)
- less reliance on github

**Comment by garrying** [comment]
Down for getting a Digital Ocean droplet and setting up. Are there other options we should consider?

**Comment by dcwalk** [comment]
I think this should be a lower priority than all the other aspects (e.g. budget, venue...) so I'd rather not focus on this until we have some critical decisions made

**Comment by darkdrgn2k** [comment]
If you need a host with unmetered bandwidth you can try FranTech (if your intention is streaming and such and think 1 tb it not enough from Digital Ocean :) )

https://buyvm.net/kvm-dedicated-server-slices 

Sadly his servers are down in the states but prices are good and such.

**Comment by dcwalk** [comment]
Hey! @garrying -- sent you an invite to a DO team for ournetworks, now that we've got a bunch of things out of the way and the CFP launched seems like a time to circle back?

I'll have time for a switch on the weekend, but if other people are keen, by all means. Also if you want to be added to the DO team let me know & what email to send to.

**Comment by dcwalk** [comment]
Heeeeeeey, so I got a little turned around in the best way to think about deploy from master, as it looks like [jekyll-hook](https://github.com/developmentseed/jekyll-hook) is no longer maintained.

Going with Travis CI, I figure we should aim to use that for deploy, but then there are waaaayz to deal with that too (I think...?)

1. use `after_success` and git webhook?
  - https://docs.travis-ci.com/user/deployment/custom/
  - https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps

2. use `script` and `deploy.sh`
  - https://docs.travis-ci.com/user/deployment/script/
 
I was sort of learning toward 2, and mocked up something _totally fake_ because I don't know what I'm doing, also I think sshpass & scp are like probably really bad ways to go about this, but the only pattern I was finding was curl+ftp and that isn't what we've got:
https://github.com/ournetworks/ournetworks.ca/pull/7

So.... halp? @garrying and @patcon?

**Comment by patcon** [comment]
Facts/feelings from my perspective:

:mag: GitHub Pages alone doesn't allow custom domain with HTTPS.
:mag: Cloudflare can be used to provide HTTPS.
:mag: AWS Cloudfront [can be used](http://strd6.com/2016/02/github-pages-custom-domain-with-ssltls/) to provide HTTPS.
:mag: Either Cloudfront of Cloudflare middle services result in full route encryption if github.io (no CNAME) ==https==> middle service ==https==> browser
:heart: I don't feel need to liberate from GitHub Pages, because it doesn't feel like lock-in.
:heart: GitHub Pages feels convenient.
:heart: GitHub Pages feels like simpler access/permissions compared to a server.
:heart: I feels HTTPS is very important
:heart: Cloudflare feels gross.
:bulb: Use aws cloudfront to provide true HTTPS in front of GitHub Pages website

**Comment by patcon** [comment]
Also, maybe I'm missing what "fancy things" is :)

also also, if there are principled, cred-based reasons to leave GitHub Pages, I can't argue with those feleings. I feel similarly to this GitHub Pages thing as I would to leaving GitHub for GitLab -- won't block, but not particularly feeling energized to do the leg-work myself :)

**Comment by dcwalk** [comment]
Thanks for the facts/feels @patcon, gonna try and follow suit!

**Comment by dcwalk** [comment]
Facts/feelings from my perspective:

(Disclaimer: I'm -0 on ditching GitHub Pages for this.)

:mag: GitHub Pages alone doesn't allow custom domain with HTTPS +1
:mag: We want to also host content over IPFS/Dat #12 
:mag: We have used a pattern of DO+managing acct and publishing on other projects (tomesh) that is well documented [tomeshnet/documents]
:mag: Conference emphasises exploring p2p, DIWO, decent, infra
:heart: HTTPS is critical
:heart: GitHub Pages feels convenient +1
:heart: I feel it is important to put into practice/act according to the ideas we care about
:heart: GitHub Pages feels easier to set up
❤️ I'm often on the fence about using GitHub
:heart: Cloudflare and Cloudfront feel not great about using to make GitHub Pages HTTPS enabled
❤️  If there is a way to have a deployment workflow also accomodate our eventual other publishing plans (including IPDS/Dat), that would be my preference

**Comment by patcon** [comment]
your mention of IPFS sells me on it! Sorry, wasn't thinking that context. So it's going to be a bit more complex soon anyhow (for good reason!) and might as well figure out the flow now :tada:

**Comment by patcon** [comment]
+1 to travisCI based approach for deploy. perk of using `script` step (instead of `after_success`) is that failed deploys cause the build badge to show the failure. failures in `after_success` are kinda swallowed.

Mind if I get DO access too, and I'll see if I can help? Same old email ;)

**Comment by garrying** [comment]
Really into the facts/feelings. Seems like we're moving towards Travis CI deploys.
@patcon are you putting together a first pass? I ran through setting it up on a test repo/droplet, and I think I have a sense of steps to get it working. [This post](https://github.com/janosrusiczki/janosrusiczki/blob/master/_posts/2018-01-25-use-travis-to-build-and-deploy-your-jekyll-site-through-ssh.markdown), at a high-level, captures what I tried.

A possible alternative to jekyll-hook: [webhook](https://github.com/adnanh/webhook) + a script to do the build and deploy.

**Comment by dcwalk** [comment]
Hey! I spun up a droplet on the DO acct which is set up to the point of actual deploying of the things.
@garrying I'll make a usr for you too? lmk key!

**Comment by garrying** [comment]
## Manual Deploy Notes (Mar 10)
The following are steps and references for setting up Certbot (Let's Encrypt) and deploying the site manually until we finalize ournetworks/ournetworks.ca#7.

### Manual Deploys
1. Clone `ournetworks/ournetworks.ca` repository: `git clone https://github.com/ournetworks/ournetworks.ca.git`
2. Install gems: `bundle install`
3. Build site: `bundle exec jekyll build`
4. SCP contents of `_site` to the server: `cp -r _site/. <username>@<serverip>:/var/www/html`

Permissions: Users who are in the `www-data` group have the ability to update the website. Adding a user to the group can be done through: `sudo usermod -aG www-data <username>`. Possible plan for moving forward on Travis CI: Create a `travisci` user and add it to `www-data`.

---
### Nginx Server Blocks
A detailed step-by-step can be [referenced here](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04).
- Site files are placed in `/var/www/html/`
- `ournetworks.ca` server block file can be found in: `/etc/nginx/sites-available/ournetworks.ca`
- In order to get `404` error pages to render from the correct template the following was added to the server block:
  ```
        error_page 404 /404.html;
  ```
- Small fix for `/cfp` redirect: https://github.com/ournetworks/ournetworks.ca/commit/b6535ff84d8f67cffba9f3525a80044ba5b93c96

### Let's Encrypt
[Refenced this guide](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04) on installing Certbot.
- Both `ournetworks.ca` and `www.ournetworks.ca` are under` https` and served via `http2`
- A cron task was installed, part of the Certbot install, under `/etc/cron.d` to renew any certificates that are about to be renewed

**Comment by dcwalk** [comment]
Where we are at: @patcon gonna take a stab at it today 🎉 🎉

**Comment by garrying** [comment]
Closing with https://github.com/ournetworks/ournetworks.ca/pull/7
